### ISSUE TITLE
[Bug]  'check invitations' under 'manage teams' when logged as admin throws an error

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/covid-alert-portal#162] opened 2020-08-11 15:04 UTC
![image (2)](https://user-images.githubusercontent.com/25329319/89914053-6f8ef680-dbc2-11ea-8bc4-d0ac397fa633.png)

**Comment by pcraig3** [comment] 2020-08-11 18:09
can't reproduce this error. Closing the issue.

**Closed by pcraig3** 2020-08-11 18:09 UTC
