### ISSUE TITLE
Change to https://register.covid-hcportal.cdssandbox.xyz/en/privacy

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#598] opened 2021-06-09 20:52 UTC
In the English version, the third paragraph , “Make a COVID Alert QR code poster", has a single quotation mark at the end [']
Please change it to a double quotation mark ["].

Thanks!

**Comment by dsamojlenko** [comment] 2021-06-14 19:03
Closing as duplicate of #594

**Closed by dsamojlenko** 2021-06-14 19:03 UTC
